### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by zagarolo** [3d-gussner/Prusa-Firmware#40]
I have a height problem of carriage Y extruder slams in the pot how can I change the end of the stroke find the new zero point? I modified bearings with double bearing under the carriage Y but increased height

**Comment by 3d-gussner** [comment]
@zagarolo did you ask on in the Prusa forum or Prusa github?

**Comment by 3d-gussner** [comment]
@zagarolo what kind of y-bearings did you use and how did you attached them? What is the height difference?

**Comment by 3d-gussner** [comment]
Closing issue due no update
