### ISSUE TITLE
Hyperfine Calibration STL Link Missing

### ISSUE THREAD

**Issue by QuentinWalker** [3d-gussner/Prusa-Firmware#42]
Hi,

I have the MK2S MMU and I wanted to download the hyperfine_calibration STL.  It looks like that link if broken.   Can you fix or point me to another source?  

Thanks

**Comment by 3d-gussner** [comment]
@QuentinWalker Thanks for pointing out. SORRY
Link is fixed and updated few things in that release. Hope that helps.

**Comment by 3d-gussner** [comment]
@QuentinWalker Did you find it? can i close the iusse?

**Comment by QuentinWalker** [comment]
Yes it works.  Thank you.

**Comment by 3d-gussner** [comment]
Solved close the issue
