### ISSUE TITLE
Prusa Mk2s

### ISSUE THREAD

**Issue by strongbow1** [3d-gussner/Prusa-Firmware#54]
After bed levelling, it goes to start then runs to the right spits out the filament asking to load filament. I load new Filament then the cycle repeats itself all the time.

**Comment by 3d-gussner** [comment]
Hi,  did you read the release notes carefully? As this firmware expects a filament run out sensor connected, you need to to the LCD menu disable/enable/disable the FRS if you don't connect a sensor.

**Comment by strongbow1** [comment]
Yes the FRS is disabled 

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by 3d-gussner** [comment]
Moin moin.

Some users have that issue some not, so please disable/enable/disable it to make sure that the right value is written to the eeprom.

**Comment by strongbow1** [comment]
I will try again and let you know. Thank you for your help

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by 3d-gussner** [comment]
Moin moin,

did it work?

**Comment by strongbow1** [comment]
Hello sorry Yes it worked. Cycled it on and off a few times then checked the end stops and now its good. But since it has the FRS active I am busy building a FRS for my prusa.

Thank you again for your help. Keep up the good work.

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by 3d-gussner** [comment]
Great,  thanks for the feedback. Glad you are building a FRS for your MK2/s :-)
Read the FRS section in the release notes. You can use M119 to see the status (if enabled) and also turn it on/off (no config change) during the print via tune menu.

Would be great if you could post a picture of your FRS and how Hyperfine Bed Leveling improved your printer.

**Comment by strongbow1** [comment]
Did the hyperfine print and turned out really food minimal changes. It was hard choice optical or mechanical. So I went with mechanical. More reliable. Once it is done I will send you a pic

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by 3d-gussner** [comment]
How is it working?

**Comment by strongbow1** [comment]
Is going good. Opted for optical sensor. Am waiting for the parts to arrive.

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by 3d-gussner** [comment]
Hope you have more luck with the optical sensor. Some filaments didn't work that good with an optical one so i switched to a mechanical one.

**Comment by 3d-gussner** [comment]
Close the issue ... thanks for the feedback
