### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by PatrikTheDev** [3d-gussner/Prusa-Firmware#55]
Is this project dead? Sure looks like it

**Comment by PatrikTheDev** [comment]
Sorry, I see the progress on the zaribo firmware

**Comment by 3d-gussner** [comment]
Hi Patrik,

The Hyperfine bed leveling got on hold at this moment as there are other great workarounds like manual level the bed with and without spring washers AND 7x7 mesh bed leveling. Maybe I will start again with Hyperfine bed leveling if really needed.
