### ISSUE TITLE
Forum links dead

### ISSUE THREAD

**Issue by Moonchill** [3d-gussner/Prusa-Firmware#58]
Prusa seems to have switched to a new forum setup, which means all of the forum links in the article are no longer working. Some of the threads you can find again by searching the forums, but that doesn't really work for very long threads where the link is to a specific post many pages into the thread.

**Comment by 3d-gussner** [comment]
@Moonchill Thanks, i will try to update these in the release notes. Or maybe even copy important things.
Sorry for the late answer.

**Comment by 3d-gussner** [comment]
Just updated the release notes:
https://github.com/3d-gussner/Prusa-Firmware/releases/tag/MK25-v3.1.3-HP
https://github.com/3d-gussner/Prusa-Firmware/releases/tag/v3.1.0-001-HFM
and Wiki
https://github.com/3d-gussner/Prusa-Firmware/wiki/How-to:-Use-Hyperfine-Bed-Leveling

Hope didn't  forget one

**Comment by Moonchill** [comment]
This got lost in my mail box. Links are fixed, and again sorry for the slow response. Closing this.
