### ISSUE TITLE
Question: How to add ramps board

### ISSUE THREAD

**Issue by boelle** [3d-gussner/Prusa-Firmware#60]
Sorry for the abuse of the issue list, but i want to try and port the prusa firmware to run on ramps/mega

what would i need to change? just asking for pointers so i have a starting point, 

i have a mendel90 printer that i almost run as a mk2.5, i dont think that using the mk3 would be wise as that would require to much hardware mods to the ramps board

will close this one again so it does not clutter the issue list to much

**Comment by boelle** [comment]
trying this one: https://www.thingiverse.com/thing:2607463

i just had to figure the difference between mk2 and mk2.5 and what the S brings to the plate

**Comment by cimoalpacino** [comment]
I've ported Prusa fw version 3.6.0, 3.7.0 and 3.8.0 to ramps.
https://github.com/cimoalpacino/Prusa-Firmware/tree/MK3_3.8.0_RAMPS?files=1

Ps: version 3.8.0 v2 from my github does not work after i tested it, due to 16-bit timers used. V1 should work fine

**Comment by boelle** [comment]
@cimoalpacino will have a look at it, but is it for the mk2 or mk3 ?

**Comment by boelle** [comment]
i looked at the files and i see ramps added, but not in the files in the /Firmware/variants/ folder

so are there a bit of setup to do that i have missed?

**Comment by boelle** [comment]
@cimoalpacino think i got it

you took the config options from the files in 

and put them in Firmware/Configuration.h ?? i see a lot of /*RAMPS*/

**Comment by 3d-gussner** [comment]
Just a question: Why don't you fork it yourself and add the Issue tab? It is a checkbox under settings.

**Comment by 3d-gussner** [comment]
Don't mis understand me wrong.  It is okay for me you abuse this here, but to document your issues it would make more sense if you have it in your own repository.

**Comment by boelle** [comment]
hehe, its more me asking questions to understand what he did. its not an issue as such, just my head that is a "tad" slow :-D

**Comment by 3d-gussner** [comment]
@cimoalpacino you can go under settings in your fork and activate issue reports. That would make more sense, than having the discussion somewhere else than here.
@boelle NP I was just surprised to get an email notification that there was a Issue report in my github. As it is quite time ago that I released any firmware.

**Comment by 3d-gussner** [comment]
@boelle he has issue open in his https://github.com/cimoalpacino/My-Prusa-Firmware/issues repository

**Comment by boelle** [comment]
and i just posted there :-D just a few questions to get my head going

**Comment by 3d-gussner** [comment]
I like the idea and my have a look at @cimoalpacino fork ...

**Comment by boelle** [comment]
yep, the reason why i'm after this is that i have a frankenbuild of a mendel90 with prusa x axis and mk42 bed (with pinda probe of course)

i use prusa slicer and i have selected the mk2s printer and only changed the start and stop gcode and i added octoprint settings, other than that i run my printer as a mk2s

and since marlin keeps changing stuff i dont like i got the idea: hey you have a mega2560 and you got those prem. ramps boards from spain, why not see if you can run prusa firmware on it

**Comment by cimoalpacino** [comment]
sorry to spam @3d-gussner :)  
will reply to @boelle back on my page.
cheers

**Comment by boelle** [comment]
and if it helps blame me for the spamming, i did start it :-D
(also the reason i closed it so quick)
