### ISSUE TITLE
4x6 Mesh Bed Leveling

### ISSUE THREAD

**Issue by gregsaun** [3d-gussner/Prusa-Firmware#68]
**Printer type** - Bear 2.1 MK3S with Hemera extruder
**MMU Upgrade** - None

**Is your enhancement related to a problem? Please describe.**
With the increase of different type of extruders on Prusa printers, it would be interesting to have an easy mesh bed leveling that naturally avoid magnets
  
**Describe the solution you'd like**
The solution would be a 4x6 MBL as seen in this picture:
![pusa_mbl_4x6](https://user-images.githubusercontent.com/12335098/74369557-dc713180-4dd5-11ea-8eec-fa77bfccce72.jpg)

Please find attached Fusion 360 files for 24v and 12v MK54 beds.
[4x6_mesh_bed_leveling.zip](https://github.com/3d-gussner/Prusa-Firmware/files/4194588/4x6_mesh_bed_leveling.zip)

**Comment by Moorviper** [comment]
I tried that grid on my bear 2.1 with rrf and it looks like that it works relatively good
![Bildschirmfoto 2023-08-22 um 13 02 43](https://github.com/3d-gussner/Prusa-Firmware/assets/3305254/ff6d7bc1-88e7-45af-9af9-2bc54014b67b)
![Bildschirmfoto 2023-08-22 um 13 00 44](https://github.com/3d-gussner/Prusa-Firmware/assets/3305254/9922fe28-b187-4727-bf86-a37d4ed378b6)

**Comment by Moorviper** [comment]
I did the nylock mod and this is how the mesh looks like

![Bildschirmfoto 2023-08-22 um 18 23 59](https://github.com/3d-gussner/Prusa-Firmware/assets/3305254/05c0892a-af70-4a0f-b695-68a96c0bbeda)
![Bildschirmfoto 2023-08-22 um 18 25 48](https://github.com/3d-gussner/Prusa-Firmware/assets/3305254/eed1f5ca-186f-42e0-8b2b-3f774347b331)
