### ISSUE TITLE
📑Report: Retraction test results

### ISSUE THREAD

**Issue by 3d-gussner** [3d-gussner/Prusa-Firmware#72]
# [Update 5 June 2020]: Report moved to [Prusa3d-Test-Object](https://github.com/prusa3d/Prusa3D-Test-Objects/issues/11) please don't comment anymore here.
Please report here your Retraction test results.

Use the 3mf file below and try to pint it with PETG or some other material that tends to be stringy.
[Container_50x20_NoCore_v2.zip](https://github.com/3d-gussner/Prusa-Firmware/files/4585431/Container_50x20_NoCore_v2.zip)

- Printer: MK2.5, MK2.5s, MK3, MK3s
- MMU: MMU1, MMU2, MMU2s
- Firmware version printer and MMU
- Bad to good scale : 0 - 10

Feel free to write additional information you want to share.

I will try to update following table so everyone can see what results we got from the community.

|Printer | MMU | PFW | MFW |K value| Quality | User |
| ------ | ------- | ---------- | ---- | ------- | --------- | -------- |
| MK3s | N/A | 3.8.1 | N/A |66| 2 | Average |
| MK3s | N/A | 3.9.0-RC3 | N/A |66| 0 | Average |
| MK3s | N/A | 3.9.0-RC3 | N/A |0.11| 9 | Average |
|  |  | |  |  |  |  |  |  |  |
| MK3s | N/A | 3.8.1 | N/A |66| 2 |  Vossberger |
| MK3s | N/A| 3.9.0-RC3 | N/A |66| 0 |  Vossberger |
| MK3s | N/A | 3.9.0-RC3 | N/A |0.11| 9| Vossberger |

**Comment by Vossberger** [comment]
MK3s, no mmu, Ruby Nozzle, SD-Card, Nunus "Transparent hellblau" PETG 

FW3.8.1 K66           very stringy (!), Extrusion up to 160% necessary, Result =2
FW3.9.0-rc3 K66     looks like one complete body, extrusion=100%, Result=0
FW3.9.0-rc3 K0.11  no string, extrusion=100%, Result=9

(Photo from bottom to top : FW3.8.1 / FW3.9.0rc3 LA1.0 / FW3.9.0rc3 LA1.5)
![A](https://user-images.githubusercontent.com/44831869/81287035-5bd37180-9062-11ea-843e-63dfe92ef0b1.jpg)

**Comment by wavexx** [comment]
Who-ho.. massive difference. I'm missing part of the discussion. How K66 /  K0.11 are chosen?

**Comment by Vossberger** [comment]
> Who-ho.. massive difference. I'm missing part of the discussion. How K66 / K0.11 are chosen?

I used https://marlinfw.org/tools/lin_advance/k-factor.html and set the K-Value best for this filament for FW3.8.1 and did a second round for FW3.9-rc3 with LA1.5

**Comment by 3d-gussner** [comment]
The LA1.0 to LA1.5 conversion is way off for this filament with K=0.21 vs. real LA15 K=0.11.
So the issue is in the conversion OR in the initial LA1.0 K value
```
Send: M900 K66
Recv: LA10C: Linear Advance mode: 1.0
Recv: LA10C: Adjusted E-Jerk: 4.50
Recv: echo:Advance K=0.21
Recv: ok
```
**Looking at other PETG profiles**, they all have LA1.0 M900 K45 which is very close to the LA1.5 K=0.11
```
[...]
Send: M900 K45
Recv: LA10C: Linear Advance mode: 1.0
Recv: LA10C: Adjusted E-Jerk: 4.50
Recv: echo:Advance K=0.13
Recv: ok
```
@Vossberger Can you please rerun the k-factor for **LA10** for your PETG? I really think there is the problem as all other tests/results with PETG were nearly the same as with FW3.8.1

**Comment by Vossberger** [comment]
Once again to this test set. It is possible that I did not adjust the eSteps before changing the FW again (I use a 0.9 stepper [415 -> 830].
