### ISSUE TITLE
📑Report: Octoprint M112 fix

### ISSUE THREAD

**Issue by 3d-gussner** [3d-gussner/Prusa-Firmware#76]
Please  report back your experience with FW3.9.1 M112 Fix.
Please follow this pattern and see blow for what we are looking for.

- Begin with actual stable firmware FW3.9.0
- Check if possible with Octorprint 3.12 and Octoprint 1.4.x
  - Switch on serial logging in Octoprint
  - Check Octoprint connected via USB
  - Check Octoprint connected via RPi port (if possible)
- Update firmware to FW3.9.1-DEVEL

What are we looking for?
Issue is that sometimes Octoprint sends M112 emergency code which will stop the print when it shouldn't.
Test procedure:
- Connect to Octoprint and search for connection issues.
- Try to make Octoprint send M112 to the printer by resetting the printer or something like that.
- Also check if there is any scenario left where "start\n" is not sent.

**Comment by brinkeb** [comment]
Did not have the time to do all tests but I´ve just finished a 15 hour print with 3.9.1 dev and Octoprint 1.4.0 without any issues.

**Comment by Vossberger** [comment]
Checked with FW3.9.0 Octoprint v1.4.0 "Detailed LCD Progress Plugin V0.2.5" on two printers (Z320 BE) 
=> 5 x Logs related to prints between 2 hours up to 14 hours checked , 
=> NO(zero) M112

second round with FW3.9.1 to come

**Comment by leptun** [comment]
@Vossberger the M112 happens because of manual reset of the printer. It should never happen during normal printing.

**Comment by Vossberger** [comment]
I checked the serial log files .. as far as I understood it should (after enabling in menu) being shown there ? correct or not ?
